### ISSUE TITLE
Create understandable explanation and UI for contrallability/reachability sets

### ISSUE THREAD

**Issue by ilyapoz** [hr0nix/BlueSkies#18]
Currently it might be not so clear for not-into-optimal control people what this means.

**Comment by hr0nix** [comment]
Firstly, I think we shouldn't using the word "set". "Points" is a less technical alternative.
Secondly, controllability set is called "конус возможностей" in Russian.

**Comment by ilyapoz** [comment]
I plan on doing the following: create good icons and provide a comprehensive tooltip. Icons and the explanation will hopefully be clear and the name will not be so important.

**Comment by hr0nix** [comment]
IMHO, creating good icons for this stuff is way harder then coming up with a comprehensible two-word description. But I'm ok with you giving it a go :)

**Comment by hr0nix** [comment]
Looks good except that tooltips are missing.

**Comment by ilyapoz** [comment]
We need a good icon for steady point.
