### ISSUE TITLE
Right column doesn't fit even on a high resolution screen

### ISSUE THREAD

**Issue by hr0nix** [hr0nix/BlueSkies#32]
Let's consider using a smaller font and moving some elements (like language and metric/imperial selectors) to the same line.

**Comment by ilyapoz** [comment]
@hr0nix, what do you think now?
I'm going to create icons for steady point and reachability set buttons. It should improve #18 too.

**Comment by hr0nix** [comment]
![screen](https://f.cloud.github.com/assets/4273011/2054109/c2f16d86-8ab0-11e3-8a6b-6abd1cb1fb42.jpg)

**Comment by hr0nix** [comment]
![screen2](https://f.cloud.github.com/assets/4273011/2054188/a566cb5c-8ab1-11e3-8cfe-57c2f0acd837.jpg)

**Comment by hr0nix** [comment]
Looks good to me.
