### ISSUE TITLE
Extravagant LZs

### ISSUE THREAD

**Issue by ilyapoz** [hr0nix/BlueSkies#47]
Your ideas on interesting places to land at.

**Comment by ilyapoz** [comment]
Ordinary DZ: Dubai
Extravagant: egypt, pyramids

**Comment by hr0nix** [comment]
Extravagant: Red square, deep blue hole, maybe rooftop of some building with a helipad.

**Comment by ilyapoz** [comment]
Some ideas from my brainstorming with a russian friend: 

что-нибудь у китайской стены

:heavy_plus_sign:  Sphinx in Giza
Ну Дубай естессна
Красная площадь
площадь святого петра

http://www.noupe.com/photography/40-bizarre-and-cool-google-earth-photos.html

http://en.wikipedia.org/wiki/List_of_city_squares_by_size

Пентагон

централ парк хорошо узнаваем сверху
остров свободы
эйфелева башня
площадь сан марко
Пизанская башня
колизей
елисейские поля с триумфальной аркой, правда там мало места
тианьмень
