### ISSUE TITLE
v2 design issues

### ISSUE THREAD

**Issue by hr0nix** [hr0nix/BlueSkies#69]
1. Is there a way to make "Got it" green and "Skip tutor" red? I think it's worth doing, currently it's reaally easy to accidentally click the wrong button.
2. Can we use the same width for the DZ selector and the DZ search (and, possibly the same font settings). It's sort of painful to look at them.
3. It's not always clear what controls is the tutorial referring to. For instance, when it's talking about the 3 buttons, its position is almost the same as when it was talking about wind settings. Some sort of arrow would certainly help, but I understand it's too much for this release, so you can ignore this.
4. "To read this tutor again, press "Restart tutor"."  ->  "To read this tutor again, click "restart the tutor"."
5. Can you use centered vertical alignment for github logo and "check out on github"?
6. I suggest an improvement for the text of the legend: 

Right-click on any place on the map to start the simulation.

Use arrows to control the canopy: left and right to steer, up and down to use brakes.

**Comment by ilyapoz** [comment]
The same _width_ or _height_ for DZ selector and DZ search?
Btw, they got misaligned during some css tweaking I don't really remember. Maybe a good case for `git bisect`!

**Comment by ilyapoz** [comment]
On the topic of highlighting the elements the tutor refers to: I can make them jump and jiggle. Is that an option?

**Comment by hr0nix** [comment]
Sorry, I meant height. Also, jump and jiggle sounds good)

**Comment by ilyapoz** [comment]
Bisect rocks. The alignment issue was introduced in af38802478ce62de0c2f8139e424b2825f13cbb5
