### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by hr0nix** [hr0nix/BlueSkies#9]
- "Направление" -> "Направление ветра"
- Units haven't been translated
- Legend container should probably automatically grow for the russian text to fit.

**Comment by hr0nix** [comment]
- "Неподвижная точка" has quotes on left-hand side only in legend.
- "Маленькя" -> "Маленькая"
- "Маленькя красная точка это ваш купол." is missing a dash.

**Comment by ilyapoz** [comment]
on legend container: it should be a separate issue.
